// Global Canonical Arknights Lore & Terminology Glossary for Russian Translation
export const ARKNIGHTS_CANONICAL_GLOSSARY: Record<string, string> = {
  // Key Organizations & Factions
  "Rhodes Island": "Родос Айленд",
  "Rhodes Island Pharmaceuticals": "Фармацевтическая компания «Родос Айленд»",
  "Reunion": "Воссоединение",
  "Reunion Movement": "Движение «Воссоединение»",
  "Lungmen Guard Department": "Департамент Гвардии Лунмэня",
  "L.G.D.": "ДГЛ",
  "LGD": "ДГЛ",
  "Penguin Logistics": "Логистика «Пингвин»",
  "Blacksteel": "Блэкстил",
  "Blacksteel Worldwide": "Блэкстил Ворлдвайд",
  "Rhine Lab": "Рейн Лаб",
  "Victoria": "Виктория",
  "Ursus": "Урсус",
  "Ursus Empire": "Империя Урсус",
  "Yen": "Янь",
  "Lungmen": "Лунмэнь",
  "Kazimierz": "Казимеж",
  "Laterano": "Латерано",
  "Leithanien": "Лейтания",
  "Columbia": "Колумбия",
  "Sami": "Сами",
  "Siracusa": "Сиракузы",
  "Higashi": "Хигаси",
  "Minos": "Минос",
  "Kjerag": "Кьераг",
  "Iberia": "Иберия",
  "Aegir": "Эгир",
  "Sargon": "Саргон",
  "Siesta": "Сиеста",
  "Rim Billiton": "Рим Биллитон",
  "Bolívar": "Боливар",
  "Abyssal Hunters": "Охотники Бездны",
  "Babel": "Бабель",
  "Dublinn": "Дублинн",
  "Glasgow": "Глазго",
  "Karlang Trade CO.": "Торговая компания Карлан",
  "Silverash Corporation": "Корпорация Сильвераш",
  "Lee's Detective Agency": "Детективное агентство Ли",
  "Sui": "Суй",
  "Seaborn": "Сиборны",
  "Church of the Deep": "Церковь Глубин",
  "Witch King": "Король-Ведьмак",

  // Races / Sub-species
  "Sankta": "Санкта",
  "Sarkaz": "Сарказ",
  "Feline": "Фелин",
  "Cautus": "Каутус",
  "Kuranta": "Куранта",
  "Lupo": "Лупо",
  "Vouivre": "Вуивр",
  "Draco": "Драко",
  "Caprinae": "Каприна",
  "Elafia": "Элафия",
  "Itra": "Итра",
  "Zalak": "Залак",
  "Perro": "Перро",
  "Forte": "Форте",
  "Anaty": "Анати",
  "Liberi": "Либери",
  "Savra": "Савра",
  "Archosauria": "Архозаврия",
  "Anura": "Анура",
  "Aslan": "Аслан",
  "Pythia": "Пифия",
  "Durin": "Дурин",
  "Manticore": "Мантикора",
  "Chimera": "Химера",
  "Cerato": "Церато",
  "Rebbah": "Ребба",

  // Core Lore World Concepts & Terms
  "Originium": "Ориджиниум",
  "Oripathy": "Орипатия",
  "Infected": "Заражённые",
  "Non-Infected": "Незаражённые",
  "Catastrophe": "Катастрофа",
  "Catastrophes": "Катастрофы",
  "Catastrophe Messenger": "Вестник Катастроф",
  "Originium Arts": "Искусства Ориджиниума",
  "Arts": "Искусства",
  "Caster": "Кастер",
  "Operator": "Оперативник",
  "Operators": "Оперативники",
  "Mobile City": "Мобильный город",
  "Nomadic City": "Мобильный город",
  "Chernobog": "Чернобог",
  "Landship": "Сухопутный корабль",
  "Doctor": "Доктор",
  "Kal'tsit": "Кальцит",
  "Amiya": "Амия",
  "Ch'en": "Чэнь",
  "Talulah": "Талула",
  "Mephisto": "Мефисто",
  "Faust": "Фауст",
  "Skullshatterer": "Череполом",
  "Crownslayer": "Краунслеер",
  "W": "W",
  "Ines": "Инес",
  "Hoederer": "Хёдерер",
  "Patriot": "Патриот",
  "FrostNova": "ФростНова",
  "Theresa": "Тереза",
  "Theresis": "Терезис",
  "Guard": "Гвардеец",
  "Medic": "Медик",
  "Sniper": "Снайпер",
  "Defender": "Защитник",
  "Supporter": "Саппорт",
  "Specialist": "Специалист",
  "Vanguard": "Авангард"
};
