import fs from 'fs';
import path from 'path';

/**
 * Syncs src/data/operator_names_map.json from src/data/operators_database.json
 * Run via: npm run sync:operators
 */

const dbPath = path.resolve('./src/data/operators_database.json');
const outputPath = path.resolve('./src/data/operator_names_map.json');

if (!fs.existsSync(dbPath)) {
  console.error(`❌ Database file not found at ${dbPath}`);
  process.exit(1);
}

try {
  const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));
  const map = {};

  const ruNames = {
    // 1-star & Robots
    'Lancet-2': 'Ланцет-2',
    'Castle-3': 'Кастл-3',
    'THRM-EX': 'Термал-EX',
    'Thermal-EX': 'Термал-EX',
    "'Justice Knight'": 'Джастис Найт',
    '"Justice Knight"': 'Джастис Найт',
    'Justice Knight': 'Джастис Найт',
    'Terra Research Commission': 'Исследовательская комиссия Терры',
    'U-Official': 'U-Официал',
    'Friston-3': 'Фристон-3',
    'PhonoR-0': 'ФоноR-0',
    'CONFESS-47': 'CONFESS-47',

    // 2-star
    'Yato': 'Ято',
    'Noir Corne': 'Нуар Корн',
    'Rangers': 'Рейнджерс',
    'Durin': 'Дурин',
    '12F': '12F',

    // 3-star
    'Fang': 'Фанг',
    'Vanilla': 'Ванилла',
    'Plume': 'Плюм',
    'Melantha': 'Меланта',
    'Popukar': 'Попукар',
    'Cardigan': 'Кардиган',
    'Beagle': 'Бигл',
    'Spot': 'Спот',
    'Kroos': 'Крус',
    'Adnachiel': 'Аднахиэль',
    'Lava': 'Лава',
    'Hibiscus': 'Гибискус',
    'Ansel': 'Ансель',
    'Steward': 'Стюард',
    'Orchid': 'Оркид',
    'Catapult': 'Катапульта',
    'Midnight': 'Миднайт',

    // Reserve Operators
    'Reserve Operator - Melee': 'Резервный оперативник (Ближний бой)',
    'Reserve Operator - Defender': 'Резервный оперативник (Защитник)',
    'Reserve Operator - Sniper': 'Резервный оперативник (Снайпер)',
    'Reserve Operator - Logistics': 'Резервный оперативник (Логистика)',
    'Reserve Operator - Caster': 'Резервный оперативник (Кастер)',
    '预备干员-术师': 'Резервный оперативник (Кастер)',
    '预备干员-狙击': 'Резервный оперативник (Снайпер)',
    '预备干员-先锋': 'Резервный оперативник (Авангард)',
    '预备干员-近卫': 'Резервный оперативник (Гвардеец)',
    '预备干员-特种': 'Резервный оперативник (Специалист)',
    '预备干员-医疗': 'Резервный оперативник (Медик)',
    '预备干员-重装': 'Резервный оперативник (Защитник)',
    '预备干员-辅助': 'Резервный оперативник (Поддержка)',

    // 4-star
    'Haze': 'Хейз',
    'Gitano': 'Гитано',
    'Greyy': 'Грей',
    'Click': 'Клик',
    'Indigo': 'Индиго',
    'Pudding': 'Пудинг',
    'Jessica': 'Джессика',
    'Meteor': 'Метеор',
    'Vermeil': 'Вермей',
    'May': 'Мэй',
    'Shirayuki': 'Сираюки',
    'Pinecone': 'Пайнкон',
    'Ambriel': 'Амбриэль',
    'Aciddrop': 'Эйсиддроп',
    'Totter': 'Тоттер',
    'Caper': 'Кейпер',
    'Courier': 'Курьер',
    'Scavenger': 'Скавенджер',
    'Vigna': 'Винья',
    'Myrtle': 'Миртл',
    'Beanstalk': 'Бинсталк',
    '冬时': 'Дунши',
    'Dobermann': 'Доберманн',
    'Matoimaru': 'Матоимару',
    'Conviction': 'Конвикшн',
    'Frostleaf': 'Фростлиф',
    'Estelle': 'Эстель',
    'Mousse': 'Мусс',
    'Cutter': 'Каттер',
    'Utage': 'Утагэ',
    'Arene': 'Арен',
    'Luo Xiaohei': 'Ло Сяохэй',
    'Quartz': 'Кварц',
    'Humus': 'Гумус',
    '骋风': 'Чэнфэн',
    'Gravel': 'Гравель',
    'Jaye': 'Джей',
    'Rope': 'Роуп',
    'Myrrh': 'Мирра',
    'Gavial': 'Гавиал',
    'Sussurro': 'Суссурро',
    'Perfumer': 'Парфюмер',
    'Purestream': 'Пьюрстрим',
    'Chestnut': 'Честнат',
    'Matterhorn': 'Маттерхорн',
    'Cuora': 'Куора',
    'Bubble': 'Баббл',
    'Lutonada': 'Лютонада',
    'Gummy': 'Гуми',
    'Dur-nar': 'Дур-нар',
    'Deepcolor': 'Дипколор',
    'Earthspirit': 'Эртспирит',
    'Podenco': 'Поденко',
    'Roberta': 'Роберта',
    'Ethan': 'Итан',
    'Shaw': 'Шоу',
    'Verdant': 'Вердант',
    '云迹': 'Юньцзи',
    'Beehunter': 'Бихантер',
    'Jackie': 'Джеки',

    // 5-star
    'Ptilopsis': 'Птилопсис',
    'Breeze': 'Бриз',
    '瑰盐': 'Гуйянь',
    'Zima': 'Зима',
    'Texas': 'Техас',
    'Chiave': 'Кьяве',
    'Poncirus': 'Понцирус',
    'Tulip': 'Тюльпан',
    'Kestrel': 'Кестрел',
    '松桐': 'Сунтун',
    'Reed': 'Рид',
    'Wild Mane': 'Уайлд Мейн',
    'Fang the Fire-Sharpened': 'Фанг Закалённая Огнём',
    'Elysium': 'Элизиум',
    'Wanqing': 'Ваньцин',
    'Blacknight': 'Блэкнайт',
    '渡桥': 'Дуцяо',
    'Cantabile': 'Кантабиле',
    'Puzzle': 'Паззл',
    '齐尔查克': 'Чилчак',
    '寻澜': 'Сюньлань',
    'Swire': 'Свайр',
    'Whislash': 'Вислаш',
    'Bryophyta': 'Бриофита',
    'Doc': 'Док',
    'Franka': 'Франка',
    'Flamebringer': 'Флеймбрингер',
    'Morgan': 'Морган',
    'Sharp': 'Шарп',
    '莱欧斯': 'Лайос',
    'Indra': 'Индра',
    'Flint': 'Флинт',
    'Dagda': 'Дагда',
    'Lappland': 'Лаппланд',
    'Ayerscarpe': 'Айерскарп',
    'Leto': 'Лето',
    'Wind Chimes': 'Уинд Чаймс',
    'Bibeak': 'Бибик',
    'Tachanka': 'Тачанка',
    'Specter': 'Спектр',
    'Broca': 'Брока',
    'Fuze': 'Фьюз',
    'Astesia': 'Астезия',
    'Sideroca': 'Сидерока',
    'Akafuyu': 'Акафую',
    'Rathalos S Noir Corne': 'Раталос S Нуар Корн',
    'La Pluma': 'Ла Плюма',
    'Highmore': 'Хаймор',
    'Tequila': 'Текила',
    'Odda': 'Одда',
    '聆音': 'Линъинь',
    '祐天寺若麦': 'Ютэнзи Вакаба',
    'Blue Poison': 'Блю Пойзон',
    'Platinum': 'Платина',
    'GreyThroat': 'Грейтроут',
    'Stormeye': 'Штормай',
    'April': 'Эйприл',
    'Kroos the Keen Glint': 'Крус Сияющий Взгляд',
    'Insider': 'Инсайдер',
    'Meteorite': 'Метеорит',
    'Sesa': 'Сеса',
    'Jieyun': 'Цзеюнь',
    'Executor': 'Экзекутор',
    'Aosta': 'Аоста',
    '吉星': 'Цзисин',
    'Amiya': 'Амия',
    'Absinthe': 'Абсент',
    'Tomimi': 'Томими',
    'Qanipalaat': 'Канипалаат',
    'Skyfire': 'Скайфайр',
    'Pith': 'Пит',
    'Leizi': 'Лэйцзы',
    'Astgenne': 'Астгенн',
    'Beeswax': 'Бизвакс',
    'Leonhardt': 'Леонхардт',
    'Santalla': 'Сантала',
    'Mint': 'Минт',
    'Iris': 'Айрис',
    'Harmonie': 'Гармония',
    'Delphine': 'Дельфина',
    'Lava the Purgatory': 'Лава Чистилища',
    'Corroserum': 'Корросерум',
    'Aroma': 'Арома',
    'Kjera': 'Кьера',
    'Rockrock': 'Рокрок',
    'Minimalist': 'Минималист',
    'Diamante': 'Диаманте',
    'Warmy': 'Ворми',
    'Miss.Christine': 'Мисс Кристин',
    '特克诺': 'Текно',
    'Mayer': 'Майер',
    'Scene': 'Сцена',
    '衡沙': 'Хэнша',
    'Silence': 'Сайленс',
    'Warfarin': 'Варфарин',
    'Folinic': 'Фолиник',
    'Touch': 'Тач',
    '录武官': 'Лу Угуань',
    'Ceylon': 'Цейлон',
    'Whisperain': 'Висперейн',
    '诺威尔': 'Новелл',
    'Tuye': 'Туйе',
    'Mulberry': 'Малберри',
    'Honeyberry': 'Ханиберри',
    'Harold': 'Гарольд',
    'Hibiscus the Purifier': 'Гибискус Очистительница',
    'Vendela': 'Вендела',
    'Paprika': 'Паприка',
    '莎草': 'Шацао',
    'Nearl': 'Нирл',
    'Hung': 'Ханг',
    'Bassline': 'Басслайн',
    '森西': 'Сэнши',
    'Projekt Red': 'Проект Ред',
    'Waai Fu': 'Вай Фу',
    'Kafka': 'Кафка',
    'Mr. Nothing': 'Мистер Ничто',
    '裁度': 'Цайду',
    'Liskarm': 'Лискарм',
    '深巡': 'Шэньсюнь',
    'Croissant': 'Круассан',
    'Bison': 'Бизон',
    'Vulcan': 'Вулкан',
    '折桠': 'Чжэя',
    'Asbestos': 'Асбестос',
    'Shalem': 'Шалем',
    'Czerny': 'Черни',
    'Blitz': 'Блиц',
    'Heavyrain': 'Хэвирейн',
    'Ashlock': 'Эшлок',
    'Firewhistle': 'Файрвистл',
    'Aurora': 'Аврора',
    'Cement': 'Цемент',
    '菲莱': 'Филай',
    'Provence': 'Прованс',
    'Melanite': 'Меланит',
    'Firewatch': 'Файрвотч',
    'Andreana': 'Андреана',
    'Lunacub': 'Лунакаб',
    'Toddifons': 'Тоддифонс',
    'Erato': 'Эрато',
    'Greyy the Lightningbearer': 'Грей Несущий Молнию',
    'Coldshot': 'Колдшот',
    '水灯心': 'Шуй Дэнсинь',
    'Spuria': 'Спурия',
    'Cliffheart': 'Клиффхарт',
    'Snowsant': 'Сноусант',
    'Almond': 'Алмонд',
    'Pramanix': 'Праманикс',
    'Shamare': 'Шамаре',
    '海霓': 'Хайни',
    'Istina': 'Истина',
    'Glaucus': 'Глаукус',
    'Proviso': 'Провизо',
    'Grain Buds': 'Грейн Бадс',
    'Windflit': 'Виндфлит',
    '凯瑟琳': 'Кэтрин',
    '阿兰娜': 'Аланна',
    'Sora': 'Сора',
    'Heidi': 'Хайди',
    '三角初华': 'Мисуми Уика',
    'Tsukinogi': 'Цукиноги',
    'Nine-Colored Deer': 'Девятицветный Олень',
    'Quercus': 'Кверкус',
    '行箸': 'Синчжу',
    'Valarqvin': 'Валарквин',
    '波卜': 'Бобу',
    'Manticore': 'Мантикора',
    'Kirara': 'Кирара',
    '八幡海铃': 'Яхата Умири',
    'FEater': 'Клиффхарт (FEater)',
    'Enforcer': 'Энфорсер',
    'Robin': 'Робин',
    'Frost': 'Фрост',
    '钼铅': 'Муцянь',
    'Bena': 'Бена',
    'Kazemaru': 'Каземару',
    'Iana': 'Яна',
    '若叶睦': 'Вакаба Муцуми',
    '锡人': 'Оловянный Человек',
    '蒂比': 'Тиби',
    'Nightmare': 'Найтмер',
    'Grani': 'Грани',
    'Savage': 'Сэвидж',

    // 6-star
    'Exusiai': 'Эксузай',
    'Archetto': 'Аркетто',
    'Ash': 'Эш',
    'Schwarz': 'Шварц',
    'Pozëmka': 'Позёмка',
    'Fartooth': 'Фартус',
    '蕾缪安': 'Лемуэн',
    'W': 'W',
    'Fiammetta': 'Фиамметта',
    'Rosa': 'Роса',
    'Typhon': 'Тифон',
    'Rosmontis': 'Росмонтис',
    "Wiš'adel": "Виш'адель",
    "Ch'en the Holungday": 'Чэнь Праздничная',
    'Ray': 'Рэй',
    '娜仁图亚': 'Нарантуя',
    'Siege': 'Сидж',
    'Bagpipe': 'Бэгпайп',
    'Saga': 'Сага',
    '忍冬': 'Лоницера',
    'Saileach': 'Сейлиш',
    'Flametail': 'Флеймтейл',
    '郁金香': 'Тюльпан (6★)',
    'Vigil': 'Виджил',
    'Muelsyse': 'Мюльсис',
    'Ines': 'Инес',
    'Ifrit': 'Ифрит',
    'Mostima': 'Мостима',
    'Eyjafjalla': 'Эйяфьялла',
    'Ceobe': 'Цеоба',
    "Ho'olheyak": "Хо'олхейак",
    'Logos': 'Логос',
    'Dusk': 'Даск',
    '玛露西尔': 'Марсиль',
    'Passenger': 'Пассажир',
    'Carnelian': 'Карнелиан',
    'Lin': 'Линь',
    'Goldenglow': 'Голденглоу',
    '荒芜拉普兰德': 'Лаппланд Пустошей',
    'Ebenholz': 'Эбенхольц',
    '妮芙': 'Нив',
    '烛煌': 'Чжухуан',
    '真言': 'Мантра',
    '死芒': 'Смертельный Луч',
    'Gnosis': 'Гнозис',
    'Angelina': 'Анджелина',
    'Suzuran': 'Судзуран',
    'Raidian': 'Райдиан',
    'Magallan': 'Магеллан',
    '电弧': 'Электродуга',
    'Skadi the Corrupting Heart': 'Скади Испорченное Сердце',
    'Civilight Eterna': 'Цивилайт Этерна',
    'Silence the Paradigmatic': 'Сайленс Парадигмальная',
    '遥': 'Яо',
    'Ling': 'Лин',
    'Stainless': 'Стейнлесс',
    'Virtuosa': 'Виртуоза',
    '酒神': 'Дионис',
    'Phantom': 'Фантом',
    'Texas the Omertosa': 'Техас Омертоза',
    'Kirin R Yato': 'Кирин R Ято',
    '弑君者': 'Краунслеер',
    'Misery': 'Мизери',
    'Lee': 'Ли',
    'Swire the Elegant Wit': 'Свайр Элегантный Ум',
    'Weedy': 'Види',
    'Aak': 'Аак',
    '新约能天使': 'Эксузай Нового Завета',
    'Gladiia': 'Гладия',
    'Mizuki': 'Мизюки',
    'Ascalon': 'Аскалон',
    'Specter the Unchained': 'Спектр Раскованная',
    'Dorothy': 'Дороти',
    'Ela': 'Эла',
    '引星棘刺': 'Торнс Ведущий Звезды',
    'Shining': 'Шайнинг',
    'Nightingale': 'Найтингейл',
    "Kal'tsit": 'Кальцит',
    'Lumen': 'Люмен',
    'Eyjafjalla the Hvít Aska': 'Эйяфьялла Белый Пепел',
    'Reed the Flame Shadow': 'Рид Тень Пламени',
    'Mon3tr': 'Mon3tr',
    'Hoshiguma': 'Хошигума',
    'Mechanist': 'Механист',
    'Saria': 'Сария',
    'Blemishine': 'Блемишайн',
    'Shu': 'Шу',
    'Nian': 'Ниан',
    'Mudrock': 'Мадрок',
    'Penance': 'Пенанс',
    'Eunectes': 'Эвнектес',
    'Horn': 'Хорн',
    'Jessica the Liberated': 'Джессика Освобождённая',
    '信仰搅拌机': 'Смеситель Веры',
    '余': 'Юй',
    '斩业星熊': 'Хошигума Рассекающая Карму',
    'Mountain': 'Маунтин',
    'Chongyue': 'Чунъюэ',
    'SilverAsh': 'Сильвераш',
    'Thorns': 'Торнс',
    'Qiubai': 'Цюбай',
    '丰川祥子': 'Тогава Сакико',
    'Hoederer': 'Хёдерер',
    '乌尔比安': 'Ульпиан',
    '佩佩': 'Пепе',
    "Ch'en": 'Чэнь',
    'Irene': 'Ирен',
    'Degenbrecher': 'Дегенбрехер',
    'Blaze': 'Блейз',
    'Gavial the Invincible': 'Гавиал Непобедимая',
    'Surtr': 'Суртр',
    'Viviana': 'Вивиана',
    '维娜·维多利亚': 'Сидж (Вина Виктория)',
    'Hellagur': 'Хеллагур',
    'Zuo Le': 'Цзо Лэ',
    'Pallas': 'Паллада',
    'Nearl the Radiant Knight': 'Нирл Сияющий Рыцарь',
    'Lessing': 'Лессинг',
    'Executor the Ex Foedere': 'Экзекутор Завета',
    '隐德来希': 'Энтелехия',
    'Młynar': 'Млынар',
    '司霆惊蛰': 'Лэйцзы Повелительница Грома',
    'Skadi': 'Скади'
  };

  for (const op of db) {
    const id = op.id || '';
    const nameEn = op.nameEn || op.nameZh || id;
    const nameZh = op.nameZh || '';

    let cleanId = id.toLowerCase()
      .replace(/^char_/, '')
      .replace(/^\d+_/, '')
      .replace(/_[a-z0-9]+$/, '');

    const parts = id.split('_');
    let charNameKey = parts.length > 2 ? parts[2] : parts[1] || id;

    const ruName = ruNames[nameEn] || ruNames[nameZh] || nameEn;

    const entry = {
      displayName: nameEn,
      englishName: nameEn,
      chineseName: nameZh,
      russianName: ruName
    };

    if (id) map[id] = entry;
    if (id) map[id.toLowerCase()] = entry;
    if (cleanId) map[cleanId] = entry;
    if (charNameKey) map[charNameKey] = entry;
    const cleanEn = nameEn.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (cleanEn) map[cleanEn] = entry;
  }

  fs.writeFileSync(outputPath, JSON.stringify(map, null, 2), 'utf8');
  console.log(`✅ [SYNC SUCCESS] Updated ${outputPath} (${Object.keys(map).length} lookup keys derived from ${db.length} operators)`);
} catch (e) {
  console.error(`❌ [SYNC FAILED] ${e.message}`);
  process.exit(1);
}
